### ISSUE TITLE
upload releases to GCP via Github Actions

### ISSUE THREAD

**Issue by ghost** [layerzzzio/raspberryapi#68]
**Description**
Upload the binaries to their GCP bucket automatically with Github Actions.

We are going to add 3 entities in the release.yml:

1) authentication to GCP using https://github.com/google-github-actions/auth#examples
2) setting gcloud using https://github.com/google-github-actions/setup-gcloud
3) uploading the release using a gcloud command from the cloud SDK

**Comment by layerzzzio** [comment]
not necessary anymore as the package is now open source
